import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemedToaster } from '@/components/ui/toaster'
import { ThemeProvider } from '@/components/theme-provider'

const geistSans = Geist({
  variable: "--font-Open_Sans-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-Open_Sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
          <ThemedToaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
