name: Build and deploy Node.js app to Azure Web App - dailyblessings

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Copy standalone output
        run: |
          cp -r .next/standalone ./standalone
          cp -r public ./standalone/public
          cp -r .next/static ./standalone/.next/static

      - name: Zip artifact for deployment
        run: zip -r release.zip ./standalone

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D59079CA3874323ADD79F3185E3286B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_461CD26D2A17437399B39E9937D8D19E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_107B9E6475F04A49A81B8877FB1624AC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dailyblessings'
          slot-name: 'Production'
          package: ./standalone
